version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "silvhua"
github_repo = "expense-classifier-backend"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::741448954840:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-DTDndgFQG40N"
cloudformation_execution_role = "arn:aws:iam::741448954840:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-6DXVH5iFbOoX"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-qnispfd7tk9w"
image_repository = "741448954840.dkr.ecr.us-west-2.amazonaws.com/docker-lambda-datajam"
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::741448954840:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-HD1r4hlHFI8h"
cloudformation_execution_role = "arn:aws:iam::741448954840:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-PiXgVMpsfpry"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-fwun9qczjrfh"
image_repository = "741448954840.dkr.ecr.us-west-2.amazonaws.com/docker-lambda-datajam"
region = "us-west-2"
